actstream/runtests/urls.py
import os
from django.contrib import admin
from django.views.static import serve
try:
    from django.urls import include, url
except ImportError:
    from django.conf.urls import include, url


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', serve,
        {'document_root': os.path.join(os.path.dirname(__file__), 'media')}),
    url(r'auth/', include('django.contrib.auth.urls')),
    url(r'testapp/', include('testapp.urls')),
    url(r'', include('actstream.urls')),
]

actstream/urls.py
try:
    from django.urls import url
except ImportError:
    from django.conf.urls import url

from actstream import feeds, views


urlpatterns = [
    # User feeds
    url(r'^feed/$', feeds.UserActivityFeed(), name='actstream_feed'),
    url(r'^feed/atom/$', feeds.AtomUserActivityFeed(),
        name='actstream_feed_atom'),
    url(r'^feed/json/$', feeds.UserJSONActivityFeed.as_view(),
        name='actstream_feed_json'),

    # Model feeds
    url(r'^feed/(?P<content_type_id>[^/]+)/$',
        feeds.ModelActivityFeed(), name='actstream_model_feed'),
    url(r'^feed/(?P<content_type_id>[^/]+)/atom/$',
        feeds.AtomModelActivityFeed(), name='actstream_model_feed_atom'),
    url(r'^feed/(?P<content_type_id>[^/]+)/json/$',
        feeds.ModelJSONActivityFeed.as_view(),
        name='actstream_model_feed_json'),

    # Object feeds
    url(r'^feed/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        feeds.ObjectActivityFeed(), name='actstream_object_feed'),
    url(r'^feed/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/atom/$',
        feeds.AtomObjectActivityFeed(), name='actstream_object_feed_atom'),
    url(r'^feed/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/json/$',
        feeds.ObjectJSONActivityFeed.as_view(),
        name='actstream_object_feed_json'),

    # Follow/Unfollow API
    url(r'^follow/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        views.follow_unfollow, name='actstream_follow'),
    url(r'^follow_all/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        views.follow_unfollow, {'actor_only': False},
        name='actstream_follow_all'),
    url(r'^unfollow_all/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        views.follow_unfollow, {'actor_only': False, 'do_follow': False},
        name='actstream_unfollow_all'),
    url(r'^unfollow/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        views.follow_unfollow, {'do_follow': False},
        name='actstream_unfollow'),

    # Follower and Actor lists
    url(r'^followers/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        views.followers, name='actstream_followers'),
    url(r'^following/(?P<user_id>[^/]+)/$',
        views.following, name='actstream_following'),
    url(r'^actors/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        views.actor, name='actstream_actor'),
    url(r'^actors/(?P<content_type_id>[^/]+)/$',
        views.model, name='actstream_model'),

    url(r'^detail/(?P<action_id>[^/]+)/$', views.detail, name='actstream_detail'),
    url(r'^(?P<username>[^/]+)/$', views.user, name='actstream_user'),
    url(r'^$', views.stream, name='actstream'),
]

extras/dashboard/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^auth-settings/$', views.AuthSettingsView.as_view(),
        name='auth_settings'),
    url(r'^backup-tokens/$', views.BackUpTokensView.as_view(),
        name='backup_tokens'),
    url(r'^create-payment-request/$', views.CreatePaymentRequestView.as_view(),
        name='create_payment_request'),
    url(r'^help/$', views.HelpSupportView.as_view(),
        name='help'),
    url(r'^load-currencies/', views.LoadCurrency.as_view(), name='load_currency'),
    url(r'^payment-request/(?P<pk>\d+)/$', views.PaymentRequestDetailView.as_view(),
        name='payment_request_detail'),
    url(r'^payment-invoice/(?P<encrypted_pk>.+)/$$', views.PaymentInvoiceTemplateView.as_view(),
        name='payment_invoice'),
    url(r'^transactions/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/(?P<year>[0-9]{4})/$',
        views.AllPaymentListView.as_view(), name='all_payment_list'),
    url(r'^transactions/payment-requests/$',
        views.PaymentRequestListView.as_view(), name='payment_requests'),
    url(r'^transactions/customer-payments/$',
        views.CustomerPaymentListView.as_view(), name='customer_payments'),
    url(r'^transactions/deleted-transactions/$',
        views.DeletedTransactionsListView.as_view(), name='deleted_transactions'),
    url(r'^transactions/catalogue/$',
        views.CataloguePaymentListView.as_view(), name='catalogue_payments'),
    url(r'^transactions/e-commerce/$',
        views.ECommerceListView.as_view(), name='e_commerce_list'),
    url(r'^transactions/shopify/$',
        views.ThirdPartyListView.as_view(), name='third_party_list'),
    url(r'^actions/$', views.ActionListView.as_view(),
        name='actions'),
    url(r'^transactions/actions/$', views.TransactionActionView.as_view(),
        name='transaction_actions'),
    # url(r'^transactions/export/(?P<file_format>\w+)/$', views.TransactionListView.as_view(), name='export'),
    url(r'^transactions/cancel/(?P<pk>\d+)/$', views.CancelTransactionView.as_view(),
        name='cancel_transaction'),
    url(r'^send-communication-event/(?P<transaction_pk>\d+)/(?P<event_type>\w+)$',
        views.send_communication_event, name='send_communication_event'),
    url(r'^transactions-graph/$',
        views.PaymentTransactionGraphView.as_view(), name='transaction_graph'),
    url(r'^push-transactions/$',
        views.PushPaymentTransactionViewSet.as_view(), name='push_transactions'),
    url(r'^bulk/', include('extras.dashboard.bulk.urls', namespace='bulk')),

]

knpay/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.admin import AdminSite
from django.views.generic import RedirectView
from django.views.i18n import javascript_catalog
from django.utils.translation import ugettext_lazy as _

from two_factor.urls import urlpatterns as tf_urls

from api.views import ECommerceAPIView, DashboardAPIView
from .views import ReportView, ExpiredView
from extras.dashboard.views import send_communication_event
from config.models import Config


def bad(request):
    """ Simulates a server error """
    1 / 0


js_info_dict = {
    'domain': 'djangojs',
    'packages': ('knpay',)
}

try:
    c = Config.get_solo()
    if hasattr(c, 'enable_2fa_on') and c.enable_2fa_on == c.ALL:
        from two_factor.admin import AdminSiteOTPRequired
        admin.site.__class__ = AdminSiteOTPRequired
except Exception as e:
    import logging
    logger = logging.getLogger('config')
    logger.exception('Error accessing config model %s' % e)

AdminSite.site_header = _('Administration')
AdminSite.site_title = _('Site admin')
AdminSite.index_title = _('Administration')

urlpatterns = [
    url(r'', include(tf_urls)),
    url(r'^api/', include('legacy.urls', namespace='legacy')),

    url(r'^api/v1/', include('extras.account.rest_api', namespace='account')),
    url(r'^api/v1/', include('api.rest_api', namespace='apis')),
    url(r'^pbl/', include('api.public_urls', namespace='public_api')),

    url(r'^bad/$', bad),
    url(r'^expired/$', ExpiredView.as_view(), name='expired'),
    url(r'^pos/crt/$',
        ECommerceAPIView.as_view({'post': 'create'}), name='pos_create'),
    url(r'^rp/$', ReportView.as_view()),
    url(r'^pos/d/crt/$', DashboardAPIView.as_view({'post': 'create'}), name='pos_d_create'),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='javascript-catalog'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^kp/', include('gateway.kpay.urls', namespace='kpay')),
    url(r'^kt/', include('gateway.knet.urls', namespace='knet')),
    url(r'^ms/', include('gateway.migs.urls', namespace='migs')),
    url(r'^bn/', include('gateway.burgan.urls', namespace='burgan')),
    url(r'^cs/', include('gateway.cybersource.urls', namespace='cs')),
    url(r'^pp/', include('gateway.pp.urls', namespace='paypal')),
    url(r'^mpgs/', include('gateway.mpgs.urls', namespace='mpgs')),
    url(r'^gw/', include('gateway.urls', namespace='gateway')),
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^activity/', include('actstream.urls')),
    url(r'^spf/', include('plugins.shopify.urls', namespace='shopify')),
    url(r'^messenger/', include('messenger.urls',namespace='messenger')),
    url(r'^dbmail/', include('dbmail.urls')),
]

urlpatterns += i18n_patterns(
    url(r'^pos/', include('extras.ui.urls', namespace='ui')),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^%s/' % settings.ADMIN_URL, admin.site.urls, name='admin'),
    url(r'^calendar/', include('schedule.urls')),
    url(r'^', include('extras.dashboard.urls', namespace='dashboard')),
    url(r'^', include('extras.account.urls', namespace='accounts')),
    url(r'^', include('plugins.urls', namespace='plugins')),
)

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if 'rest_framework_swagger' in settings.INSTALLED_APPS:
    from rest_framework_swagger.views import get_swagger_view

    schema_view = get_swagger_view(title='Knpay API',
                                   patterns=[
                                       url(r'^api/v1/',
                                           include('extras.account.rest_api',
                                                   namespace='account')),
                                       url(r'^api/v1/', include('api.rest_api',
                                                                namespace='apis')),
    url(r'^send-communication-event/(?P<transaction_pk>\d+)/(?P<event_type>\w+)$',
        send_communication_event, name='send_communication_event'),
                                   ])

    urlpatterns += [url(r'^api-docs/$', schema_view)]

handler404 = 'knpay.views.handler404'
handler500 = 'knpay.views.handler500'

extras/dashboard/forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import logging

from django import forms
from django.utils.translation import ugettext_lazy as _
from django.core import validators

from actstream import action
from intl_tel_input.widgets import IntlTelInputWidget

from sms.models import SMSAuthConfig
from gateway.models import PaymentTransaction
from utils.forms import BasePaymentForm, AbstractBasePaymentRequestConfigForm, AjaxBaseForm
from .models import Field
from .helpers import create_payment_req_helper

logger = logging.getLogger('dashboard')


class BasePaymentRequestForm(BasePaymentForm):
    """
    Manages sms confirmation
    Must be used in conjunction with BasePaymentForm due to self.config
    requirement.
    """
    sms_notification = forms.BooleanField(
        label=_("SMS notification"), required=False
    )
    sms_payment_details = forms.BooleanField(
        widget=forms.HiddenInput(), required=False)

    def __init__(self, *args, **kwargs):
        super(BasePaymentRequestForm, self).__init__(*args, **kwargs)

    def clean_sms_notification(self):
        sms_notification = self.cleaned_data.get('sms_notification', False)
        if sms_notification and not self.has_phone_field:
            raise forms.ValidationError(
                _("SMS cannot be sent because phone number field is missing from the form."
                  " Contact an administrator to enable it."))
        return sms_notification


class CreatePaymentRequestForm(AbstractBasePaymentRequestConfigForm,
                               BasePaymentRequestForm):
    """
    Main form for creating a payment transaction from frontend
    """
    knpay_section = PaymentTransaction.PAYMENT_REQUEST
    transaction_type = PaymentTransaction.PAYMENT_REQUEST
    generate_qr_code = forms.BooleanField(label=_('Generate QR Code'),
                                          required=False)

    def __init__(self, *args, **kwargs):
        super(CreatePaymentRequestForm, self).__init__(*args, **kwargs)

        if hasattr(self.config, 'default_email'):
            if self.config.default_email:
                self.fields['default_email'] = forms.BooleanField(
                    label=_('Use default email'), required=False)

        for field in self.config.fields.active():
            self.add_defined_field(field.get_name(), label=field.get_label(
            ), required=field.required, field=field)

        # Hide SMS Checkbox if there is no Active SMS Provider available
        if not SMSAuthConfig.objects.current():
            self.fields['sms_notification'].widget = forms.HiddenInput()
        else:
            self.fields['sms_notification'].help_text = _("Notify the customer via SMS that "
                                                          "he has to pay an invoice. Builtin "
                                                          "phone field has to be present on "
                                                          "the form.")

        if 'customer_phone' in self.fields:
            self.fields['customer_phone'].widget = IntlTelInputWidget(default_code='kw',
                                                                      preferred_countries=['kw', 'ro', 'in'])

        self.helper = create_payment_req_helper(self)
        self.helper.include_media = False

    def save(self):
        user = self.request.user
        obj = self.serializer.save(initiator=user)
        action.send(user, verb='created', action_object=obj)
        return obj

    def get_data_for_api(self):
        data = super(CreatePaymentRequestForm, self).get_data_for_api()
        # If staff has selected 'Use default email' then add a flag in extra
        if data.get('default_email', None):
            if data.get('extra', None):
                data['extra'].update({'has_default_email': 'true'})
            else:
                data['extra'] = {'has_default_email': 'true'}

        return data


class CreateHelpRequestForm(AjaxBaseForm, forms.Form):
    SUBTITLE_CHOICES = (
        ("support_request", _("Support Request")),
        ("suggestion", _("Suggestion")),
        ("feedback", _("Feedback")),
    )
    email = forms.EmailField(label=_("Email"))
    subject = forms.ChoiceField(label=_("Subject"), choices=SUBTITLE_CHOICES)
    message = forms.CharField(
                    label='Message',
                    widget=forms.Textarea(attrs={'data-override': 'content'})
                )
    def __init__(self, *args, **kwargs):
        super(CreateHelpRequestForm, self).__init__(*args, **kwargs)
        

class PaymentRequestDetailForm(BasePaymentRequestForm,
                               forms.ModelForm):

    class Meta:
        model = PaymentTransaction
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PaymentRequestDetailForm, self).__init__(*args, **kwargs)
        extra = self.instance.extra
        self.fields['currency_code'] = forms.CharField(
            label=_("Currency"), required=False)
        for key, value in extra.items():
            field = Field.objects.get_for_name(key, self.config)
            label = field.get_label() if field is not None else key
            self.add_defined_field(
                key, label=label, initial=value, field=field)

        for field in PaymentTransaction.CUSTOMER_FIELDS:
            val = getattr(self.instance, field)
            if val:
                self.add_defined_field(field, label=PaymentTransaction._meta.get_field(field).verbose_name,
                                       initial=val)
        if self.fields.get('attachment'):
            self.fields['attachment'].widget = forms.HiddenInput()

        # Hide SMS Checkbox if sms_notification not selected
        if not getattr(self.instance, 'sms_notification'):
            self.fields['sms_notification'].widget = forms.HiddenInput()

        for field in self.fields:
            self.fields[field].disabled = True

templates/dashboard/ajax/actions.html
{% load el_pagination_tags i18n %}

<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th>{% trans 'ID' %}</th>
                    <th>{% trans 'Email' %}</th>
                    <th>{% trans 'State' %}</th>
                    <th>{% trans 'Gateway code' %}</th>
                    <th>{% trans 'Amount' %}</th>
                    <th>{% trans 'Currency' %}</th>
                    <th>{% trans 'Creation date' %}</th>
                    <th>{% trans 'Send email' %}</th>
                    <th>{% trans 'Send SMS' %}</th>
                </tr>
            </thead>

            <tbody>
                {% paginate actions %}
                {% for transaction in actions %}
                    <tr>
                        <td><a href="{% url 'dashboard:payment_request_detail' transaction.pk %}">{{ transaction.id }}</a></td>
                        <td>{{ transaction.customer_email }}</td>
                        <td>{{ transaction.state | upper }}</td>
                        <td>{% if transaction.gateway_code %} {{ transaction.gateway_code }} {% else %} {% trans 'Not selected' %} {% endif %}</td>

                        <td>{{ transaction.amount }}</td>
                        <td>{{ transaction.currency_code }}</td>
                        <td>{{ transaction.created|date:"d-M-Y" }}</td>
                        <th><button {% if not transaction.is_valid_for_payment %}disabled{% endif %} data-href="{% url 'dashboard:send_communication_event' transaction.pk 'email' %}" class="btn btn-xs btn-info send-communication-event">{% trans 'MAIL' %}</button></th>
                        <th><button {% if not transaction.customer_phone_number or not transaction.is_valid_for_payment %}disabled{% endif %} data-href="{% url 'dashboard:send_communication_event' transaction.pk 'sms' %}" class="btn btn-xs btn-info send-communication-event">{% trans 'SMS' %}</button></th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<div class="row">
 
    <div class="col-md-12 text-center">
        {% include 'dashboard/_partials/pagination.html' %}
    </div>
</div>

templates/dashboard/ajax/all_transactions.html
{% load el_pagination_tags i18n listing_tags %}

<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        {% for total_currency in total_based_per_currencies %}
                            <div>{{ total_currency.total|floatformat:"3" }} {{ total_currency.currency }}</div>
                            {% empty %}
                            <div>0.000 KWD</div>
                        {% endfor %}
                        <div>{% trans 'Total Generated' %}</div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        {% for total_currency in total_paid_based_per_currencies %}
                            <div>{{ total_currency.total|floatformat:"3" }} {{ total_currency.currency }}</div>
                            {% empty %}
                            <div>0.000 KWD</div>
                        {% endfor %}
                        <div>{% trans 'Total Received' %}</div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="col-lg-3 col-md-6">
        <div class="panel panel-red">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        {% for total_currency in total_not_paid_based_per_currencies %}
                            <div>{{ total_currency.total|floatformat:"3" }} {{ total_currency.currency }}</div>
                            {% empty %}
                            <div>0.000 KWD</div>
                        {% endfor %}
                        <div>{% trans 'Net Balance' %}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-hover table-striped">
            <thead>
            <tr>
                {% if perms.gateway.delete_paymenttransaction or perms.gateway.cancel_paymenttransaction %}
                    <th><input type='checkbox' class='mark_all'></th>
                {% endif %}
                <th>{% trans 'ID' %}</th>
                <th>{% trans 'Initiator' %}</th>
                <th>{% trans 'Email' %}</th>
                <th>{% trans 'State' %}</th>
                <th>{% trans 'Gateway' %}</th>
                <th>{% trans 'Amount' %}</th>
                <th>{% trans 'Currency' %}</th>
                <th>{% trans 'Creation date' %}</th>

                <th>{% trans 'Notify' %}</th>
                {% if perms.gateway.cancel_paymenttransaction %}
                    <th>{% trans 'Cancel' %}</th>
                {% endif %}

            </tr>
            </thead>

            <tbody>
            {% paginate 10 transactions %}
            {% for transaction in transactions %}
                <tr>
                    {% if perms.gateway.delete_paymenttransaction or perms.gateway.cancel_paymenttransaction %}
                        <td><input type='checkbox' value='{{ transaction.id }}' class='action_checkbox'></td>
                    {% endif %}
                    <td><a href="{{ transaction.get_absolute_url }}">{{ transaction.id }}</a></td>
                    <td>{{ transaction.initiator.username }}</td>
                    <td>{{ transaction.customer_email }}</td>
                    <td class='state'>{{ transaction.state | upper }}</td>
                    <td>{% if transaction.gateway_code %} {{ transaction.gateway_code }} {% else %}
                        {% trans 'Not selected' %} {% endif %}</td>

                    <td>{{ transaction.amount }}</td>
                    <td>{{ transaction.currency_code }}</td>
                    <td>{{ transaction.created|date:"d-M-Y" }}</td>

                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false"
                                    {% if not transaction.is_valid_for_payment %}disabled{% endif %}>
                                {% trans 'Select event' %} <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'dashboard:send_communication_event' transaction.pk 'email' %}"
                                       class="send-communication-event">{% trans 'Email' %}</a></li>
                                {% if transaction.customer_phone %}
                                    <li><a href="{% url 'dashboard:send_communication_event' transaction.pk 'sms' %}"
                                           class="send-communication-event">{% trans 'SMS' %}</a></li>
                                {% endif %}
                                {% if transaction.push_notification %}
                                    <li><a href="{% url 'dashboard:send_communication_event' transaction.pk 'push' %}"
                                           class="send-communication-event">{% trans 'Push Notification' %}</a></li>
                                    <li><a href="{% url 'dashboard:send_communication_event' transaction.pk 'all' %}"
                                           class="send-communication-event">{% trans 'All' %}</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </td>
                    {% if perms.gateway.cancel_paymenttransaction %}
                        <td class='text-center cancel'>
                            <button type='button' action='{% url 'dashboard:cancel_transaction' transaction.pk %}'
                                    class='btn btn-default cancel_transaction'
                                    {% if not transaction.can_be_cancelled %}disabled{% endif %}>{% trans 'Cancel' %}</button>
                        </td>
                    {% endif %}
                </tr>
            {% empty %}
                <tr>
                    <td colspan="13" align="center">
                        {% trans 'No Entry Found' %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<div class="row">

    <div class="col-sm-12 text-center">
        {% include 'dashboard/_partials/pagination.html' %}
    </div>
</div>

templates/dashboard/ajax/catalogue_transactions.html
{% load el_pagination_tags i18n listing_tags %}
{% load product_tags %}
{% if total_based_per_currencies and total_paid_based_per_currencies and total_not_paid_based_per_currencies  %}
{% include 'dashboard/ajax/box_analysis.html' %}
{% endif %}
<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-hover table-striped">
            <thead>
            <tr>
                {% if perms.gateway.delete_paymenttransaction or perms.gateway.cancel_paymenttransaction %}
                    <th><input type='checkbox' class='mark_all'></th>
                {% endif %}
                <th>{% trans 'ID' %}</th>
                <th>{% trans 'Type' %}</th>
                <th>{% trans 'Product ID' %}</th>
                <th>{% trans 'Product/Service Name' %}</th>
                <th>{% trans 'Email' %}</th>
                <th>{% trans 'State' %}</th>
                <th>{% trans 'Gateway' %}</th>
                <th>{% trans 'Amount' %}</th>
                <th>{% trans 'Currency' %}</th>
                <th>{% trans 'Creation date' %}</th>
                {% for field in transaction_config.extra_fields %}<th>{{ field.get_label }}</th>{% endfor %}
                <th>{% trans 'Notify' %}</th>
                {% if perms.gateway.cancel_paymenttransaction %}
                    <th>{% trans 'Cancel' %}</th>
                {% endif %}

            </tr>
            </thead>

            <tbody>
            {% paginate 10 transactions %}
            {% for transaction in transactions %}
                <tr>
                    {% if perms.gateway.delete_paymenttransaction or perms.gateway.cancel_paymenttransaction %}
                        <td><input type='checkbox' value='{{ transaction.id }}' class='action_checkbox'></td>
                    {% endif %}
                    <td><a href="{{ transaction.get_absolute_url }}">{{ transaction.id }}</a></td>
                    <td>{{ transaction.extra.product_type }}</td> <!-- Type-->
                    {% get_product_url transaction.extra.product as product_url %}
                    <td> <a {% if product_url %} href="{{product_url}}" target="_blank" {% else %} href="#" {% endif %}>{{transaction.extra.product}}</a></td> <!-- Product id/Promotion page-->
                    <td>{{ transaction.extra.product_name }}</td> <!-- Product/Service Name-->
                    <td>{{ transaction.customer_email }}</td>
                    <td class='state'>{{ transaction.state | upper }}</td>
                    <td>{% if transaction.gateway_code %} {{ transaction.gateway_code }} {% else %}
                        {% trans 'Not selected' %} {% endif %}</td>

                    <td>{{ transaction.amount }}</td>
                    <td>{{ transaction.currency_code }}</td>
                    <td>{{ transaction.created|date:"d-M-Y" }}</td>
                    
                    {% get_values_for_extra_fields transaction as values %}
                    {% for value in values %}<td>{{ value }}</td>{% endfor %}

                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false"
                                    {% if not transaction.is_valid_for_payment %}disabled{% endif %}>
                                {% trans 'Select event' %} <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'dashboard:send_communication_event' transaction.pk 'email' %}"
                                       class="send-communication-event">{% trans 'Email' %}</a></li>
                                {% if transaction.customer_phone %}
                                    <li><a href="{% url 'dashboard:send_communication_event' transaction.pk 'sms' %}"
                                           class="send-communication-event">{% trans 'SMS' %}</a></li>
                                {% endif %}
                                {% if transaction.push_notification %}
                                    <li><a href="{% url 'dashboard:send_communication_event' transaction.pk 'push' %}"
                                           class="send-communication-event">{% trans 'Push Notification' %}</a></li>
                                    <li><a href="{% url 'dashboard:send_communication_event' transaction.pk 'all' %}"
                                           class="send-communication-event">{% trans 'All' %}</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </td>
                    {% if perms.gateway.cancel_paymenttransaction %}
                        <td class='text-center cancel'>
                            <button type='button' action='{% url 'dashboard:cancel_transaction' transaction.pk %}'
                                    class='btn btn-default cancel_transaction'
                                    {% if not transaction.can_be_cancelled %}disabled{% endif %}>{% trans 'Cancel' %}</button>
                        </td>
                    {% endif %}
                </tr>
            {% empty %}
                <tr>
                    <td colspan="13" align="center">
                        {% trans 'No Entry Found' %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<div class="row">

    <div class="col-sm-12 text-center">
        {% include 'dashboard/_partials/pagination.html' %}
    </div>
</div>