actstream/runtests/urls.py
import os
from django.contrib import admin
from django.views.static import serve
try:
    from django.urls import include, url
except ImportError:
    from django.conf.urls import include, url


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', serve,
        {'document_root': os.path.join(os.path.dirname(__file__), 'media')}),
    url(r'auth/', include('django.contrib.auth.urls')),
    url(r'testapp/', include('testapp.urls')),
    url(r'', include('actstream.urls')),
]

actstream/urls.py
try:
    from django.urls import url
except ImportError:
    from django.conf.urls import url

from actstream import feeds, views


urlpatterns = [
    # User feeds
    url(r'^feed/$', feeds.UserActivityFeed(), name='actstream_feed'),
    url(r'^feed/atom/$', feeds.AtomUserActivityFeed(),
        name='actstream_feed_atom'),
    url(r'^feed/json/$', feeds.UserJSONActivityFeed.as_view(),
        name='actstream_feed_json'),

    # Model feeds
    url(r'^feed/(?P<content_type_id>[^/]+)/$',
        feeds.ModelActivityFeed(), name='actstream_model_feed'),
    url(r'^feed/(?P<content_type_id>[^/]+)/atom/$',
        feeds.AtomModelActivityFeed(), name='actstream_model_feed_atom'),
    url(r'^feed/(?P<content_type_id>[^/]+)/json/$',
        feeds.ModelJSONActivityFeed.as_view(),
        name='actstream_model_feed_json'),

    # Object feeds
    url(r'^feed/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        feeds.ObjectActivityFeed(), name='actstream_object_feed'),
    url(r'^feed/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/atom/$',
        feeds.AtomObjectActivityFeed(), name='actstream_object_feed_atom'),
    url(r'^feed/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/json/$',
        feeds.ObjectJSONActivityFeed.as_view(),
        name='actstream_object_feed_json'),

    # Follow/Unfollow API
    url(r'^follow/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        views.follow_unfollow, name='actstream_follow'),
    url(r'^follow_all/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        views.follow_unfollow, {'actor_only': False},
        name='actstream_follow_all'),
    url(r'^unfollow_all/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        views.follow_unfollow, {'actor_only': False, 'do_follow': False},
        name='actstream_unfollow_all'),
    url(r'^unfollow/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        views.follow_unfollow, {'do_follow': False},
        name='actstream_unfollow'),

    # Follower and Actor lists
    url(r'^followers/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        views.followers, name='actstream_followers'),
    url(r'^following/(?P<user_id>[^/]+)/$',
        views.following, name='actstream_following'),
    url(r'^actors/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        views.actor, name='actstream_actor'),
    url(r'^actors/(?P<content_type_id>[^/]+)/$',
        views.model, name='actstream_model'),

    url(r'^detail/(?P<action_id>[^/]+)/$', views.detail, name='actstream_detail'),
    url(r'^(?P<username>[^/]+)/$', views.user, name='actstream_user'),
    url(r'^$', views.stream, name='actstream'),
]

extras/account/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
]

extras/dashboard/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^auth-settings/$', views.AuthSettingsView.as_view(),
        name='auth_settings'),
    url(r'^backup-tokens/$', views.BackUpTokensView.as_view(),
        name='backup_tokens'),
    url(r'^create-payment-request/$', views.CreatePaymentRequestView.as_view(),
        name='create_payment_request'),
    url(r'^help/$', views.HelpSupportView.as_view(),
        name='help'),
    url(r'^load-currencies/', views.LoadCurrency.as_view(), name='load_currency'),
    url(r'^payment-request/(?P<pk>\d+)/$', views.PaymentRequestDetailView.as_view(),
        name='payment_request_detail'),
    url(r'^payment-invoice/(?P<encrypted_pk>.+)/$$', views.PaymentInvoiceTemplateView.as_view(),
        name='payment_invoice'),
    url(r'^transactions/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/(?P<year>[0-9]{4})/$',
        views.AllPaymentListView.as_view(), name='all_payment_list'),
    url(r'^transactions/payment-requests/$',
        views.PaymentRequestListView.as_view(), name='payment_requests'),
    url(r'^transactions/customer-payments/$',
        views.CustomerPaymentListView.as_view(), name='customer_payments'),
    url(r'^transactions/deleted-transactions/$',
        views.DeletedTransactionsListView.as_view(), name='deleted_transactions'),
    url(r'^transactions/catalogue/$',
        views.CataloguePaymentListView.as_view(), name='catalogue_payments'),
    url(r'^transactions/e-commerce/$',
        views.ECommerceListView.as_view(), name='e_commerce_list'),
    url(r'^transactions/shopify/$',
        views.ThirdPartyListView.as_view(), name='third_party_list'),
    url(r'^actions/$', views.ActionListView.as_view(),
        name='actions'),
    url(r'^transactions/actions/$', views.TransactionActionView.as_view(),
        name='transaction_actions'),
    # url(r'^transactions/export/(?P<file_format>\w+)/$', views.TransactionListView.as_view(), name='export'),
    url(r'^transactions/cancel/(?P<pk>\d+)/$', views.CancelTransactionView.as_view(),
        name='cancel_transaction'),
    url(r'^send-communication-event/(?P<transaction_pk>\d+)/(?P<event_type>\w+)$',
        views.send_communication_event, name='send_communication_event'),
    url(r'^transactions-graph/$',
        views.PaymentTransactionGraphView.as_view(), name='transaction_graph'),
    url(r'^push-transactions/$',
        views.PushPaymentTransactionViewSet.as_view(), name='push_transactions'),
    url(r'^bulk/', include('extras.dashboard.bulk.urls', namespace='bulk')),

]

knpay/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.admin import AdminSite
from django.views.generic import RedirectView
from django.views.i18n import javascript_catalog
from django.utils.translation import ugettext_lazy as _

from two_factor.urls import urlpatterns as tf_urls

from api.views import ECommerceAPIView, DashboardAPIView
from .views import ReportView, ExpiredView
from extras.dashboard.views import send_communication_event
from config.models import Config


def bad(request):
    """ Simulates a server error """
    1 / 0


js_info_dict = {
    'domain': 'djangojs',
    'packages': ('knpay',)
}

try:
    c = Config.get_solo()
    if hasattr(c, 'enable_2fa_on') and c.enable_2fa_on == c.ALL:
        from two_factor.admin import AdminSiteOTPRequired
        admin.site.__class__ = AdminSiteOTPRequired
except Exception as e:
    import logging
    logger = logging.getLogger('config')
    logger.exception('Error accessing config model %s' % e)

AdminSite.site_header = _('Administration')
AdminSite.site_title = _('Site admin')
AdminSite.index_title = _('Administration')

urlpatterns = [
    url(r'', include(tf_urls)),
    url(r'^api/', include('legacy.urls', namespace='legacy')),

    url(r'^api/v1/', include('extras.account.rest_api', namespace='account')),
    url(r'^api/v1/', include('api.rest_api', namespace='apis')),
    url(r'^pbl/', include('api.public_urls', namespace='public_api')),

    url(r'^bad/$', bad),
    url(r'^expired/$', ExpiredView.as_view(), name='expired'),
    url(r'^pos/crt/$',
        ECommerceAPIView.as_view({'post': 'create'}), name='pos_create'),
    url(r'^rp/$', ReportView.as_view()),
    url(r'^pos/d/crt/$', DashboardAPIView.as_view({'post': 'create'}), name='pos_d_create'),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='javascript-catalog'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^kp/', include('gateway.kpay.urls', namespace='kpay')),
    url(r'^kt/', include('gateway.knet.urls', namespace='knet')),
    url(r'^ms/', include('gateway.migs.urls', namespace='migs')),
    url(r'^bn/', include('gateway.burgan.urls', namespace='burgan')),
    url(r'^cs/', include('gateway.cybersource.urls', namespace='cs')),
    url(r'^pp/', include('gateway.pp.urls', namespace='paypal')),
    url(r'^mpgs/', include('gateway.mpgs.urls', namespace='mpgs')),
    url(r'^gw/', include('gateway.urls', namespace='gateway')),
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^activity/', include('actstream.urls')),
    url(r'^spf/', include('plugins.shopify.urls', namespace='shopify')),
    url(r'^messenger/', include('messenger.urls',namespace='messenger')),
    url(r'^dbmail/', include('dbmail.urls')),
]

urlpatterns += i18n_patterns(
    url(r'^pos/', include('extras.ui.urls', namespace='ui')),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^%s/' % settings.ADMIN_URL, admin.site.urls, name='admin'),
    url(r'^calendar/', include('schedule.urls')),
    url(r'^', include('extras.dashboard.urls', namespace='dashboard')),
    url(r'^', include('extras.account.urls', namespace='accounts')),
    url(r'^', include('plugins.urls', namespace='plugins')),
)

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if 'rest_framework_swagger' in settings.INSTALLED_APPS:
    from rest_framework_swagger.views import get_swagger_view

    schema_view = get_swagger_view(title='Knpay API',
                                   patterns=[
                                       url(r'^api/v1/',
                                           include('extras.account.rest_api',
                                                   namespace='account')),
                                       url(r'^api/v1/', include('api.rest_api',
                                                                namespace='apis')),
    url(r'^send-communication-event/(?P<transaction_pk>\d+)/(?P<event_type>\w+)$',
        send_communication_event, name='send_communication_event'),
                                   ])

    urlpatterns += [url(r'^api-docs/$', schema_view)]

handler404 = 'knpay.views.handler404'
handler500 = 'knpay.views.handler500'

templates/_partials/menu/menu.html
{% load rules %}

{% for menu_item in menu_items %}
    {% test_rule 'has_menu_perm' user menu_item as can_view_parent %}
    {% if can_view_parent %}
        <li>
            {% if not menu_item.has_children %}
                <a href="{{ menu_item.url }}"><i class="{{ menu_item.icon }}"></i> {{ menu_item.verbose_name }}</a>
            {% else %}
                <a href="javascript:void(0)"><i class="{{ menu_item.icon }}"></i> {{ menu_item.verbose_name }}<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    {% for child in menu_item.children %}
                        {% test_rule 'has_menu_perm' user child as can_view_child %}
                        {% if can_view_child and child.visible %}
                            <li>
                                <a href="{{ child.url }}">{{ child.verbose_name }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            {% endif %}
        </li>
    {% endif %}
{% endfor %}

templates/_partials/menu/navbar_header.html
{% load solo_tags static i18n %}

{% get_solo 'config.Config' as config %}

<div class="navbar-header">
    {% if user.is_authenticated %}
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">{% trans 'Toggle navigation' %}</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    {% endif %}
    <a class="navbar-brand" {% if user.is_authenticated %} href="/" {% else %} href="javascript:void(0);" {% endif %}>{{ config.title }}</a>
</div>
<!-- /.navbar-header -->

templates/_partials/menu/navbar_right.html
{% load i18n %}

{% if user.is_authenticated %}
    <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)">
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <!--                 <li><a href="javascript:void(0)"><i class="fa fa-user fa-fw"></i>{% trans 'User profile' %}</a>
                    </li> -->
                    {% if request.user.is_superuser or request.user.is_staff %}
                        <li><a href="{% url 'admin:index' %}"><i
                                class="fa fa-gear fa-fw"></i>{% trans 'Administration panel' %}</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="{% url 'dashboard:auth_settings' %}"><i
                                class="fa fa-key fa-fw"></i>{% trans 'Auth settings' %}</a>
                        </li>
                        <li class="divider"></li>
                    {% endif %}
                    <li class='text-center'>
                        <form action="{% url 'set_language' %}" name='change_language' method="post">
                            {% csrf_token %}
                            <input name="next" type="hidden" value=""/>
                            <input name="language" type="hidden" value="{% if LANGUAGE_BIDI %}en{% else %}ar{% endif %}"/>
                            <input type="submit" class='btn btn-default' value="{% if LANGUAGE_BIDI %}Switch language{% else %}تبديل اللغة{% endif %}"/>
                        </form>
                    </li>
                    <li class="divider"></li>
                    <li><a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out fa-fw"></i>{% trans 'Logout' %}</a>
                    </li>
                </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->
{% endif %}

templates/_partials/menu/sidebar.html
{% load i18n %}

<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="{% trans 'Search...' %}">
                    <span class="input-group-btn">
                    <button class="btn btn-default" type="button">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
                </div>
                <!-- /input-group -->
            </li>
            {% include '_partials/menu/menu.html' %}
            
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->